#!/usr/bin/env ruby -w
# encoding: UTF-8
Tk内核 = TkKernel
Tk对象 = TkObject
Tk绑定 = TkBindCore
Tk主界面 = TkRoot
Tk窗口 = TkWindow
Tk标签 = TkLabel
Tk画布 = TkCanvas
Tkc组件 = TkcItem
Tkc矩形 = TkcRectangle
Tkc椭圆 = TkcOval
Tkc线段 = TkcLine
Tkc多边形 = TkcPolygon
Tkc弧形 = TkcArc
Tkc文本 = TkcText
Tkc位图 = TkcBitmap
Tkc图片 = TkcImage
Tkc窗口 = TkcWindow
Tk变量 = TkVariable