#!/usr/bin/env ruby -w
# encoding: UTF-8
Tk内核 = TkKernel
Tk对象 = TkObject
Tk主界面 = TkRoot
Tk窗口 = TkWindow
Tk标签 = TkLabel
Tk画布 = TkCanvas
Tkc文本 = TkcText
Tkc线段 = TkcLine
Tkc矩形 = TkcRectangle
Tkc椭圆 = TkcOval
Tk变量 = TkVariable